#!/bin/sh

set -e

if [ -z "$1" ]; then
    echo "build_release <version>"
    exit 1
fi

VER=$1
NOW=`date +%Y-%m-%d`

echo "Version: $VER - $NOW"

DATEh=`head -n 3 hostapd/ChangeLog | tail -n 1 | sed "s/ .*//"`

if [ "$DATEh" != "$NOW" ]; then
    echo "NOTE! Date mismatch in ChangeLog: hostapd $DATEh != $NOW"
fi

git archive --format=tar --prefix=hostapd-$VER/ HEAD \
	README COPYING src hostapd |
	gzip > $RELDIR/hostapd-$VER.tar.gz
